fix(strata-cli): better handling of low-entropy passwords warnings
alpenlabs/strata pull request #397
Opened 2024-10-09 19:40 UTC by storopoli

## Description

PR got merged before we could address some suggestions

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [x] Refactor

## Checklist

-   [ ] I have performed a self-review of my code.
-   [ ] I have commented my code where necessary.
-   [ ] I have updated the documentation if needed.
-   [ ] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [ ] New and existing tests pass with my changes.

## Related Issues

STR-493

2024-10-10 14:01 UTC, storopoli commented
This can be approved and merged since we are not touching functional tests

2024-10-10 15:07 UTC, delbonis requested changes
Minor organizational suggestions.

2024-10-10 15:07 UTC, delbonis commented on bin/strata-cli/src/seed.rs
> +                )
I would do `.unwrap_or("no feedback")` or whatever is needed to make the lifetimes work.  Also a colon instead of a period there for aesthetics.

2024-10-10 15:07 UTC, delbonis commented on bin/strata-cli/src/cmd/change_pwd.rs
> +            .as_str(),
Could we consolidate the password checking into a `validate_pass` function that does the error handling and exit when the password is insufficient?

2024-10-10 18:41 UTC, storopoli commented on bin/strata-cli/src/seed/password.rs
> +            }
![image](https://github.com/user-attachments/assets/50ddf340-3967-48fa-a937-6a374fe7a4b0)
Updated in bec4aa860b8cc0c47c27a6bd2bb1e95f147a0018

2024-10-10 18:53 UTC, AaronFeickert approved these changes
utACK

2024-10-10 18:53 UTC, AaronFeickert commented on bin/strata-cli/src/seed/password.rs
> +                "".to_string() // empty string is fine
An even cleaner approach could be to make `feedback_message` an `Option<String>`, but I wouldn't block on that.

2024-10-11 16:32 UTC, delbonis submitted a review, later dismissed

2024-10-11 19:26 UTC, storopoli commented
rebased

2024-10-11 20:11 UTC, delbonis approved these changes

2024-10-11 20:11 UTC, merged