STR-196 consolidate provider store traits
alpenlabs/strata pull request #456
Opened 2024-11-07 10:38 UTC by sapinb

## Description
* Merge *Provider and *Store traits to single *Database traits
* Adjust imports and variable names, etc as required 

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [x] Refactor
-   [ ] New or updated tests

## Checklist

-   [x] I have performed a self-review of my code.
-   [ ] I have commented my code where necessary.
-   [x] I have updated the documentation if needed.
-   [x] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [x] New and existing tests pass with my changes.

## Related Issues

2024-11-07 17:04 UTC, delbonis requested changes
Broadly looks good.

2024-11-19 06:51 UTC, sapinb commented on crates/db/src/traits.rs
> +pub trait L2Database {
Updated

2024-11-19 08:57 UTC, bewakes approved these changes

2024-11-19 21:24 UTC, delbonis approved these changes
Seems good.

2024-11-19 21:24 UTC, merged

2024-11-19 21:25 UTC, delbonis commented
Force merged because of codecov being annoying.