consensus-logic: Remove redundant messaging
alpenlabs/strata pull request #457
Opened 2024-11-07 11:47 UTC by bewakes

Make StatusRx attributes private and add wait_until_genesis

sync-worker: Remove sleep while handling block

status_manager: Restructure genesis check thread

consensus-logic: Fix state watch channel deadlock

## Description

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [ ] Refactor
-   [ ] New or updated tests

## Checklist

-   [ ] I have performed a self-review of my code.
-   [ ] I have commented my code where necessary.
-   [ ] I have updated the documentation if needed.
-   [ ] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [ ] New and existing tests pass with my changes.

## Related Issues

2024-11-07 11:49 UTC, bewakes commented
The conversation from https://github.com/alpenlabs/strata/pull/434#issuecomment-2461419745 can be continued here.

2024-11-11 17:59 UTC, delbonis requested changes
Sorry, made this review last week but forgot to actually submit it.

2024-11-19 06:36 UTC, bewakes commented on crates/consensus-logic/src/csm/worker.rs
> +                if ev_idx < *idx {
haha, just wanted to make it a bit concise.

2024-11-19 07:02 UTC, bewakes commented on crates/status/src/status_manager.rs
> +    }
Created a ticket for this
https://alpenlabs.atlassian.net/browse/STR-626

2024-11-20 02:07 UTC, delbonis requested changes
Those changes to the status tracker logic you split out as a separate ticket ideally should have been done in this PR, since you're actively working on related code that would benefit from the interface being improved.

2024-11-20 06:08 UTC, bewakes commented on crates/consensus-logic/src/fork_choice_manager.rs
> +    StateUpdate(Option<ClientState>),
This was done to make the block_on code concise, but with the new `Abort` variant, the options are removed now.

2024-11-20 06:09 UTC, bewakes commented on crates/consensus-logic/src/fork_choice_manager.rs
> +    if let Some(sync) = cs.sync() {
Totally. this was missed.

2024-11-20 06:11 UTC, bewakes commented
Actually there are other places too where the new Status interfaces will be used so will be done in the next PR, keeping this PR scoped.

2024-11-20 15:01 UTC, delbonis approved these changes
Alright this is good for now, there will probably be some more reworks in the future after the epoch rework happens but that's an issue for later.

2024-11-20 15:01 UTC, merged

2024-11-20 15:02 UTC, delbonis commented
Force merged because of codecov.