Str 597 zkvm prover
alpenlabs/strata pull request #478
Opened 2024-11-18 06:52 UTC by prajwolrg

## Description

### Type of Change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation update
-   [ ] Refactor
-   [ ] New or updated tests

## Checklist

-   [ ] I have performed a self-review of my code.
-   [ ] I have commented my code where necessary.
-   [ ] I have updated the documentation if needed.
-   [ ] My changes do not introduce new warnings.
-   [ ] I have added tests that prove my changes are effective or that my feature works.
-   [ ] New and existing tests pass with my changes.

## Related Issues

2024-11-25 13:58 UTC, storopoli requested changes
Major NIT on `anyhow` in lib crates and specially in lib traits.

Also, why are you importing a lot of `use strata_zkvm::Foo` and then in the same file referencing undeclared top level stuff with `strata_zkvm::Bar`?

If no other reason, then we should strive for consistency.

2024-11-26 03:24 UTC, delbonis submitted a review, later dismissed

2024-11-26 03:24 UTC, delbonis commented on crates/zkvm/zkvm/src/prover.rs
> +    fn prove<'a, H>(input: &'a Self::Input, host: &H) -> anyhow::Result<(Proof, Self::Output)>
Yeah things like these should all use granularly typed errors like from `thiserror`.

2024-11-26 05:50 UTC, prajwolrg commented on crates/zkvm/zkvm/src/env.rs
> +    );
In the `zkvm/src/env`, it is alright to use `unwrap()` since we expect the proof generation to fails.

2024-11-26 05:53 UTC, prajwolrg commented on crates/proof-impl/l1-batch/src/logic.rs
> +#[derive(Debug, BorshSerialize, BorshDeserialize)]
I don't think so.

2024-11-26 20:13 UTC, storopoli submitted a review, later dismissed
ACK 47dea31c67411d1ce8d6cf127430f92f45ef7430
Thanks for the errors. Looks great!

2024-11-27 04:16 UTC, MdTeach submitted a review, later dismissed

2024-11-27 16:03 UTC, storopoli commented
Oops, the conflicts are my fault because we needed to remove once and for all our `reth` fork from all `Cargo.lock`s (not the top-level one only).
If you need help rebasing let me know...

2024-11-27 16:46 UTC, prajwolrg commented
> Oops, the conflicts are my fault because we needed to remove once and for all our `reth` fork from all `Cargo.lock`s (not the top-level one only). If you need help rebasing let me know...

No worries. I have rebased and pushed again.

2024-11-27 16:52 UTC, storopoli approved these changes
ACK 6c95b8811d740f49651d73f01c9282bb8f04986b

2024-11-28 02:31 UTC, MdTeach approved these changes

2024-11-28 05:31 UTC, bewakes approved these changes

2024-11-28 05:44 UTC, merged