Fix prover client build
alpenlabs/strata pull request #526
Opened 2024-12-09 07:23 UTC by MdTeach

## Description

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactor
- [ ] New or updated tests
- [ ] Dependency Update

## Notes to Reviewers

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code where necessary.
- [ ] I have updated the documentation if needed.
- [ ] My changes do not introduce new warnings.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] New and existing tests pass with my changes.

## Related Issues

2024-12-09 10:39 UTC, storopoli requested changes
Can we also include this TODO in the PR?
https://github.com/alpenlabs/strata/blob/b5f84a04fe1f45503cb70da076e93abe3fc31554/.github/workflows/prover.yml#L51-L57

2024-12-09 11:59 UTC, evgenyzdanovich reviewed
Looks good, thanks for taking care of it! Agree with Jose, we can re-enable commented block in the `prover.yml` (I guess with `-F "sp1"`)

2024-12-09 15:50 UTC, MdTeach commented
> Can we also include this TODO in the PR?
> 
> https://github.com/alpenlabs/strata/blob/b5f84a04fe1f45503cb70da076e93abe3fc31554/.github/workflows/prover.yml#L51-L57

The `required-features = ["prover"]` attribute has been removed from the prover-client binary, so the prover-client should be built as part of a regular cargo build. Consequently, I have updated the CI by removing the corresponding TODO comment.

2024-12-09 16:05 UTC, evgenyzdanovich approved these changes

2024-12-09 18:32 UTC, delbonis approved these changes

2024-12-09 20:26 UTC, storopoli approved these changes
ACK 69d0a3ac00005983452617a9de59db852f9176c9

2024-12-10 02:58 UTC, prajwolrg approved these changes

2024-12-10 03:07 UTC, merged