STR 731: Functional test RPC Behaviour when EL is down
alpenlabs/strata pull request #556
Opened 2024-12-22 19:46 UTC by voidash

## Description

### Type of Change
Adds a functional test that checks the behavior of client RPC when reth is down and ability to continue when reth is up again

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactor
- [x] New or updated tests
- [ ] Dependency Update

## Notes to Reviewers

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented my code where necessary.
- [x] I have updated the documentation if needed.
- [x] My changes do not introduce new warnings.
- [x] I have added tests that prove my changes are effective or that my feature works.
- [x] New and existing tests pass with my changes.

## Related Issues

STR-731

2024-12-23 12:07 UTC, storopoli submitted a review, later dismissed
ACK e9cdf9d28a509446595c2ad57b89e408d4337b39

Nice work! I like the comments and the flow. It was easy to follow what was going on.

We need also an ACK from someone that has a solid knowledge of all the seq/reth RPCs that make sure that we are not missing anything.

2024-12-23 16:22 UTC, delbonis requested changes

2024-12-23 16:22 UTC, delbonis commented on functional-tests/fn_rpc_el_inactive.py
> +        )
It shouldn't stop, it should just be reporting that we can't make new blocks.

2024-12-23 16:22 UTC, delbonis commented on functional-tests/fn_rpc_el_inactive.py
> +        )
Same here.

2024-12-23 16:22 UTC, delbonis commented on functional-tests/fn_rpc_el_inactive.py
> +        )
This isn't the *sequencer* stopping if this stops happening.  Really it's the reader that would have crashed.

2024-12-24 19:22 UTC, delbonis approved these changes

2024-12-24 19:23 UTC, delbonis commented
Any idea why these other functional tests are failing?

2024-12-25 05:45 UTC, storopoli commented
> Any idea why these other functional tests are failing?

Flaky run. I've manually rerun and now passes.
I suspected a flaky run when I saw the error messages.

2024-12-25 05:46 UTC, storopoli approved these changes
ACK 4203132f08e1cc9e73b0d2f4c405b506fd9190dd

2024-12-25 06:06 UTC, merged