block template manager and rpc
alpenlabs/strata pull request #560
Opened 2024-12-24 08:37 UTC by sapinb

## Description

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactor
- [ ] New or updated tests
- [ ] Dependency Update

## Notes to Reviewers

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code where necessary.
- [ ] I have updated the documentation if needed.
- [ ] My changes do not introduce new warnings.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] New and existing tests pass with my changes.

## Related Issues

2025-01-02 21:03 UTC, delbonis requested changes
Broad strokes looks good and cleanly written.  There's a lot of stuff in here that ideally should have some unit tests, although I realize that's hard with the stuff that's being ran here.

Also, does it really make sense to use L2BlockId as the template ID?  I know it works out but it feels like it's not quite right and there should be a distinct thing that refers to templates as they're being constructed.  Not sure.

2025-01-02 21:03 UTC, delbonis commented on bin/strata-client/src/main.rs
>          ..
Don't really like how this is being cloned but I do like the idea of passing it to the thing that uses it on 449.

Could this be reworked to repeat the pattern with the other launcher fns?

2025-01-10 16:54 UTC, delbonis requested changes
I think this got rebased so the github comments got confused.  Redid review on new content, maybe duplicated some comments.

2025-01-10 16:54 UTC, delbonis commented on bin/strata-client/src/rpc_server.rs
> +            .submit_intent_async(blob_intent)
Submitting the checkpoint to L1 should be done somewhere else after we've saved it durably.  There should be something that tracks the status of these outstanding payloads.  If we've saved the signed checkpoint but we don't see a writer entry for it then we should create it.

This will have to be updated sooner or later to use the `Payload`-oriented terminology since "blob" refers more to DA.

2025-01-10 16:54 UTC, delbonis commented on bin/strata-client/src/rpc_server.rs
> +        }
Missing `return`s?

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/block_template/error.rs
> +    ConsensusError(#[from] strata_consensus_logic::errors::Error),
Should have `db:` and `consensus:` prefixes.

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/block_template/error.rs
> +    InvalidSignature(L2BlockId, Buf64),
Would make these

* `unknown block id {0}`
* `invalid signature for block {0}`

and leave it at that without actually printing the sig.  It's not really useful as something printed and makes the logs more verbose.  It's still in the type if we want to work with it internally.

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/block_template/handle.rs
See earlier comment about having some helper fn that handles submitting the message on the channel and waiting for a response so the send/receive logic doesn't have to be duplicated in each of the high level functions.

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/block_template/manager.rs
> +        self.pending_by_parent.insert(parent, block_id);
Maybe this should print a warning when evicting a child?  Or do some other handling if we're doing something weird with conflicting templates so we at least can know if it's happening.

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/block_template/manager.rs
> +}
This should probably call out to the actual validation logic instead of reimplementing it here.

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/errors.rs
> +pub enum Error {
I order these as with:

* firstparty error variants we expect to generate
* wrapper variants for errors from dependencies
* `Unimplemented`
* `Other(String)` and similar

This way we don't mix in interesting errors that we're looking for with stuff that's just wrappers.

2025-01-10 16:54 UTC, delbonis commented on functional-tests/tests/cl_checkpoint.py
> +        self.debug(f"checkpoint: {ckp_idx} found")
Just make this `info`.

2025-01-10 16:54 UTC, delbonis commented on functional-tests/factory/factory.py
> +        }
Expose RPCs data here so we can call it?

2025-01-10 16:54 UTC, delbonis commented on crates/sequencer/src/worker.rs
> +    time::{self},
Weird import.

2025-01-16 07:17 UTC, sapinb commented on crates/block-assembly/src/handle.rs
> +    }
handle has to be pub as its created in the strata-client bin.

2025-01-16 07:31 UTC, sapinb commented on functional-tests/factory/factory.py
> +        }
signer does not serve any rpcs. Its purely does signing and is stateless right now.

2025-01-16 07:32 UTC, sapinb commented on crates/sequencer/src/worker.rs
> +    time::{self},
this should have been autocorrected 😄

2025-01-16 08:35 UTC, sapinb commented on bin/strata-client/src/rpc_server.rs
> +        }
`?` used on the Err should be equivalent to returning it. Should be equivalent to 

`return Err(Error::MissingCheckpointProof(idx).into());`

2025-01-16 12:51 UTC, sapinb commented on crates/sequencer/src/block_template/error.rs
> +    ConsensusError(#[from] strata_consensus_logic::errors::Error),
updated

2025-01-16 12:52 UTC, sapinb commented on crates/sequencer/src/errors.rs
> +pub enum Error {
There were a lot of unused errors here. This has been cleaned up.

2025-01-16 12:52 UTC, sapinb commented on crates/sequencer/src/block_template/manager.rs
> +}
updated.

2025-01-16 13:06 UTC, sapinb commented on bin/strata-client/src/rpc_server.rs
> +            .submit_intent_async(blob_intent)
Currently, we are depending on the L1 writer to ensure durability, else the sequencer will receive signing duty for same checkpoint again and provide another signature. 
The durably saving part should likely come on sequencer side to prevent signing duplicate/conflicting checkpoints ?

2025-01-16 13:06 UTC, sapinb commented on crates/block-assembly/src/error.rs
> +    ConsensusError(#[from] strata_consensus_logic::errors::Error),
updated

2025-01-16 13:07 UTC, sapinb commented on crates/block-assembly/src/types.rs
> +        self.header.get_blockid()
updated

2025-01-16 13:08 UTC, sapinb commented on crates/block-assembly/src/worker.rs
> +                let _ = sender.send(manager.get_block_template(block_id));
added warning logs if this errors. 
Didnt get the `completion` instead of `sender` part though.

2025-01-16 13:08 UTC, sapinb commented on crates/block-assembly/src/types.rs
> +    }
updated

2025-01-16 13:08 UTC, sapinb commented on crates/block-assembly/src/types.rs
> +
updated

2025-01-16 13:08 UTC, sapinb commented on crates/block-assembly/src/handle.rs
> +            Ok(res) => res,
added more descriptive message

2025-01-16 13:09 UTC, sapinb commented on crates/sequencer/src/block_template/error.rs
> +    InvalidSignature(L2BlockId, Buf64),
updated.

2025-01-16 13:09 UTC, sapinb commented on crates/sequencer/src/block_template/handle.rs
updated

2025-01-16 13:49 UTC, delbonis commented on crates/block-assembly/src/handle.rs
> +    pub async fn get_block_template(&self, template_id: L2BlockId) -> Result<BlockTemplate, Error> {
This isn't what I had in mind, the main thing we want to avoid is the worker thread having to wake up unless it has to, which it has to do for a lot with this call/response style pattern.  The goal would involve removing this `GetBlockTemplate` variant.

Very loose skeleton of the structure:

```rs
struct Shared {
    templates: HashMap<SomeKey, Template>
}

struct Handle {
    shared: Arc<Mutex<Shared>>
    tx: ...
}

fn worker(rx: ..., shared: Arc<Shared>) {
    // when finish new template, put into shared.templates
}
```

Then we can always check the templates table first for the ready templates before sending of a new request.  Maybe I shouldn't have used the term "cache".

2025-01-16 13:51 UTC, delbonis requested changes

2025-01-16 13:51 UTC, delbonis commented on crates/sequencer/src/block_template/handle.rs
> +            Error::ChannelError("failed to send request to template manager, worker likely exited")
This always only happens if the channel is closed.  Just make this its own error variant.

2025-01-16 13:51 UTC, delbonis commented on crates/sequencer/src/block_template/handle.rs
> +            Err(_) => Err(Error::ChannelError("tx dropped, worker likely exited")),
Same here.

2025-01-16 13:54 UTC, delbonis commented on crates/block-assembly/src/worker.rs
> +                let _ = sender.send(manager.get_block_template(block_id));
The term "completion" is the more generally used term for what channel represents in this kind of pattern, using it instead of just "sender" makes it more clear what's happening.

I realize that conflicts with the var named "completion" here already, might have to rework that.

2025-01-16 13:55 UTC, delbonis commented on bin/strata-client/src/rpc_server.rs
> +        }
Oh I didn't see that.  Yeah that's a bit unclear.  It's fine.

2025-01-16 14:00 UTC, delbonis commented
The main issue is just fastpathing requests for already-built templates to avoid waking up the template manager thread.

2025-01-16 19:41 UTC, sapinb commented on crates/block-assembly/src/handle.rs
> +    pub async fn get_block_template(&self, template_id: L2BlockId) -> Result<BlockTemplate, Error> {
updated

2025-01-16 19:42 UTC, sapinb commented on crates/block-assembly/src/worker.rs
> +                let _ = sender.send(manager.get_block_template(block_id));
opting for response here

2025-01-16 19:43 UTC, sapinb commented on crates/sequencer/src/block_template/handle.rs
> +            Error::ChannelError("failed to send request to template manager, worker likely exited")
updated

2025-01-16 19:43 UTC, sapinb commented on crates/sequencer/src/block_template/handle.rs
> +            Err(_) => Err(Error::ChannelError("tx dropped, worker likely exited")),
updated

2025-01-17 09:44 UTC, bewakes reviewed
Looks good overall. Some nits, mostly around documents and commented out codes.

Do you think the types in the `sequencer` crate could possibly be moved to primitives? Because the `strata-sequencer-client` depends on the `sequencer` crate which also has `strata-client` specific worker/handle modules, which the `sequencer-client` has nothing to do with.

2025-01-17 11:33 UTC, sapinb commented on bin/strata-sequencer-client/src/main.rs
> +async fn duty_fetcher_worker<R>(
moved this out to separate file

2025-01-17 11:33 UTC, sapinb commented on crates/sequencer/Cargo.toml
> +# strata-rocksdb = { workspace = true, features = ["test_utils"] }
removed

2025-01-17 11:33 UTC, sapinb commented on crates/sequencer/src/block_template/handle.rs
> +pub enum TemplateManagerRequest {
updated.

2025-01-20 12:06 UTC, storopoli requested changes
Minor nits for now.

2025-01-20 12:06 UTC, storopoli commented on bin/strata-sequencer-client/Cargo.toml
> +# strata-test-utils.workspace = true
Why these are commented? Do we plan to use them in this PR? Or is this a leftover?

2025-01-20 12:06 UTC, storopoli commented on crates/sequencer/Cargo.toml
> +# rustdoc.all = "warn"
I dare you uncommenting these docs lints 😂.

2025-01-21 09:30 UTC, sapinb commented on bin/strata-sequencer-client/Cargo.toml
> +# strata-test-utils.workspace = true
Forgot to remove them. Thanks for the catch.

2025-01-21 09:30 UTC, sapinb commented on crates/sequencer/Cargo.toml
> +# rustdoc.all = "warn"
Updated the docs where possible.

2025-01-21 09:33 UTC, sapinb commented on bin/strata-sequencer-client/Cargo.toml
> +name = "strata-sequencer-client"
added new crates to CODEOWNERS

2025-01-21 09:43 UTC, storopoli commented on crates/sequencer/Cargo.toml
> -# rustdoc.all = "warn"
I mean these lints are good.
You can leave the missing_docs stuff commented out.
Can you undo this change?
Or are they already enforced at workspace level?

Cc @Rajil1213

2025-01-21 09:57 UTC, Rajil1213 commented on crates/sequencer/Cargo.toml
> -# rustdoc.all = "warn"
Yes, definitely in favor of these rustc lints (they cannot be done at the workspace level, I think).

That said, we should put it in our engineering guidelines to enable these for all new crates. For existing ones, we already have a ticket: https://alpenlabs.atlassian.net/browse/STR-198 since that would require adding documentation to all the code which is a massive undertaking.

In this case, is there a reason we are explicitly opting out of these lints if these were already enabled?

2025-01-21 10:00 UTC, Rajil1213 commented on crates/sequencer/Cargo.toml
> -# rustdoc.all = "warn"
If these were missed in some other PR and re-enabling these would require adding docs all over, I think it's fine to just remove the docs lints for now and add it to the pile in the other ticket as Jose is suggesting.

2025-01-21 10:02 UTC, storopoli commented on crates/sequencer/Cargo.toml
> -# rustdoc.all = "warn"
> I think it's fine to just remove the docs lints for now and add it to the pile in the other ticket as Jose is suggesting.

Yeah just undo the diff I've highlighted

2025-01-21 11:02 UTC, sapinb commented on .github/CODEOWNERS
> +bin/strata-sequencer-client/  @alpenlabs/bin @alpenlabs/bin-strata-client
sequencer-client is split off from strata-client and keeping it under same owners should be good for now

2025-01-21 13:28 UTC, sapinb commented on crates/sequencer/Cargo.toml
> -# rustdoc.all = "warn"
updated.

2025-01-21 17:49 UTC, Rajil1213 requested changes
Do these changes also affect the files in `docker/`? If so, could we update those as well.  
I personally use it for running the bridge node locally but there may be other use cases that I'm not aware of.

2025-01-21 18:11 UTC, delbonis submitted a review, later dismissed

2025-01-21 18:15 UTC, storopoli commented on .github/CODEOWNERS
> +bin/strata-sequencer-client/  @alpenlabs/bin @alpenlabs/bin-strata-client
Ok!

2025-01-21 18:16 UTC, storopoli submitted a review, later dismissed
ACK cc943eb011df24b012e0a54a2c3aae51bd6f62d2

2025-01-22 07:12 UTC, bewakes commented
Needs a rebase.

2025-01-28 11:53 UTC, storopoli submitted a review, later dismissed
ACK 33622c221d5f1ee60014bfd55a671a2a03c8eefe

2025-01-28 20:37 UTC, delbonis commented
What's still broken here?

2025-01-28 20:54 UTC, storopoli commented
> What's still broken here?

Might be a flaky one. Re-triggered the functional tests.

2025-01-30 09:24 UTC, storopoli commented
func tests are still failing and also the `cargo-audit`.

2025-01-30 14:15 UTC, delbonis submitted a review, later dismissed

2025-01-30 15:41 UTC, voidash submitted a review, later dismissed

2025-01-30 17:37 UTC, delbonis approved these changes

2025-01-30 18:13 UTC, sapinb commented
functional tests fixed. 
cargo audit issue will be resolved with reth update which should be done separately.

2025-01-30 18:47 UTC, delbonis commented
Looking at the flaky tests is looks like some of them have just *always* been flaking.

2025-01-30 18:47 UTC, delbonis commented
Merging now to keep the ball rolling.

2025-01-30 18:47 UTC, merged