Str 650 fn tests prover client
alpenlabs/strata pull request #566
Opened 2024-12-29 06:07 UTC by prajwolrg

## Description

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature/Enhancement (non-breaking change which adds functionality or enhances an existing one)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactor
- [ ] New or updated tests
- [ ] Dependency Update

## Notes to Reviewers

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have commented my code where necessary.
- [ ] I have updated the documentation if needed.
- [ ] My changes do not introduce new warnings.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [ ] New and existing tests pass with my changes.

## Related Issues

2025-01-02 06:57 UTC, bewakes reviewed
Looks good mostly, there seem to be places where there's TODO because of `BatchInfo` being inclusive on L1 block height range. It might be a good idea to change the inclusivity of BatchInfo and get rid of those TODOs.
Also some minor nits.

2025-01-02 06:57 UTC, bewakes commented on bin/prover-client/src/rpc_server.rs
> +                    .map_err(to_jsonrpsee_error("invalid task"))?;
> task_tracker should know it

Will the task tracker know it if we are just doing `.get_task()`?

2025-01-02 06:57 UTC, bewakes commented on functional-tests/utils.py
> +    proof_keys = prover_rpc.dev_strata_proveCheckpoint(idx)
Do you think the comment above needs to be updated?

2025-01-02 07:05 UTC, MdTeach commented on crates/btcio/src/test_utils.rs
> +pub mod corepc_node_helpers {
```suggestion
pub mod core_rpc_node_helpers {
```

2025-01-02 07:28 UTC, MdTeach commented on crates/proof-impl/cl-agg/src/lib.rs
> +    let mut cl_proof_pp_start: L2BatchProofOutput = zkvm.read_verified_borsh(cl_stf_vk);
We have snapshot as:
```rust
#[derive(Debug, Clone, BorshSerialize, BorshDeserialize)]
pub struct ChainStateSnapshot {
    pub hash: Buf32,
    pub slot: u64,
    pub l2_blockid: L2BlockId,
}
```

But just incrementing `slot` without updating other fields would be safe ?

2025-01-02 07:47 UTC, prajwolrg commented on bin/prover-client/src/args.rs
>      pub loop_interval: u64,
nice catch! thanks!

2025-01-02 07:48 UTC, prajwolrg commented on bin/prover-client/src/rpc_server.rs
> +                    .map_err(to_jsonrpsee_error("invalid task"))?;
Updated the comment

2025-01-02 07:54 UTC, prajwolrg commented on crates/proof-impl/cl-agg/src/lib.rs
> +    let mut cl_proof_pp_start: L2BatchProofOutput = zkvm.read_verified_borsh(cl_stf_vk);
Yes, it's safe for now. We need to clean up the logic to properly handle this. I've created a separate [ticket](https://github.com/alpenlabs/strata/pull/566) for that.

2025-01-02 07:55 UTC, prajwolrg commented on crates/btcio/src/test_utils.rs
> +pub mod corepc_node_helpers {
The crate name is `corepc`

2025-01-02 09:24 UTC, MdTeach submitted a review, later dismissed

2025-01-02 11:07 UTC, bewakes submitted a review, later dismissed

2025-01-02 12:35 UTC, Rajil1213 approved these changes
Approving as non-ci changes have already been approved and there are no CI-specific changes.

2025-01-02 16:36 UTC, storopoli requested changes
minor cosmetics nits

2025-01-02 16:36 UTC, storopoli commented on bin/prover-client/src/args.rs
> +    /// Defaults to 1000 milliseconds.
```suggestion
    /// Defaults to 1,000 milliseconds.
```

Help people 35+ to count zeros

2025-01-02 16:36 UTC, storopoli commented on bin/prover-client/src/args.rs
> +        default = "1000"
```suggestion
        default = "1_000"
```

2025-01-02 16:36 UTC, storopoli commented on crates/btcio/src/test_utils.rs
> +        std::env::set_var("BITCOIN_XPRIV_RETRIEVABLE", "true");
Can we import this module above?

```rs
use std::env;
```

2025-01-02 16:36 UTC, storopoli commented on crates/state/src/l1/timestamp_store.rs
> +        let initial_timestamps: [u32; 11] = std::array::from_fn(|i| (i + 1) as u32);
Can we import?

```rs
use std::array;
```

2025-01-02 22:18 UTC, delbonis requested changes
Mostly just some questions, looks good overall.

2025-01-02 22:18 UTC, delbonis commented on bin/prover-client/src/rpc_server.rs
>      }
I think we can do the weird trick with the returning a closure thing here like with `to_jsonrpsee_error`.

```rs
fn make_jsonrpc_err(m: &str) -> impl Fn(Error) -> jsonrpcerrorwhatever {
    // but simplify this
    |e| to_jsonrpsee_error_object(e, m)
}
```

2025-01-02 22:18 UTC, delbonis commented on bin/prover-client/src/rpc_server.rs
> +                Ok(format!("{:?}", status))
`format!("{status:?}")`

2025-01-02 22:18 UTC, delbonis commented on bin/prover-client/src/task_tracker.rs
> +                // task tracker prematurely would result in a TaskNotFound error.
Is it fine to just keep those tasks on-disk somewhere?

2025-01-02 22:18 UTC, delbonis commented on bin/prover-client/src/task_tracker.rs
> +                ProvingTaskStatus::Failed => "Failed",
Could we move the deps out of the status field so that we can just `Debug`/`Display` it?  If we kept the deps list as part of some task control header then that would let us visualize the trees a bit better retrospectively.

2025-01-03 00:59 UTC, prajwolrg commented on bin/prover-client/src/rpc_server.rs
>      }
Yea right that already exists!

2025-01-03 01:32 UTC, prajwolrg commented on bin/prover-client/src/task_tracker.rs
> +                // task tracker prematurely would result in a TaskNotFound error.
Yea right! Thanks!

2025-01-03 10:30 UTC, MdTeach submitted a review, later dismissed

2025-01-03 11:36 UTC, bewakes approved these changes

2025-01-03 17:59 UTC, delbonis submitted a review, later dismissed

2025-01-06 10:27 UTC, bewakes approved these changes

2025-01-06 10:38 UTC, MdTeach approved these changes

2025-01-06 14:01 UTC, storopoli approved these changes
ACK b13c83640010fd70173e8ab0f462e0d74337bd8d

2025-01-06 14:14 UTC, evgenyzdanovich reviewed
LGTM! Great stuff!

P.S. this requires a rebase with regards to recent fn-tests changes.

2025-01-06 16:49 UTC, delbonis approved these changes

2025-01-06 17:04 UTC, storopoli submitted a review, later dismissed

2025-01-06 17:04 UTC, storopoli commented on crates/btcio/src/test_utils.rs
> +    /// `address`.
```suggestion
    /// Mine a number of blocks of a given size `count`, which may be specified to a given coinbase
    /// `address`.
```

Typo

2025-01-07 10:30 UTC, bewakes approved these changes

2025-01-07 10:34 UTC, MdTeach approved these changes

2025-01-07 10:35 UTC, Rajil1213 approved these changes

2025-01-07 10:41 UTC, storopoli approved these changes
ACK ffb7ea3358b7aa63839b5ed2d384e67eff628623

2025-01-07 10:51 UTC, merged